server:
    port: 81
spring:
    application:
        name: fraud
    datasource:
        username: postgres
        url: jdbc:postgresql://localhost:5432/fraud
        password: user
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
    zipkin:
        base-url: http://localhost:9411
eureka:
  client:
      service-url:
        defaultZone: http://localhost:8761/eureka