server:
  port: 80
spring:
  application:
    name: customer
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/customer
    password: user
  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true