server:
  port: 83
spring:
  application:
    name: notification
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/notification
    password: user
  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true
  zipkin:
    base-url: http://localhost:9411
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true