server:
  port: 82
spring:
  application:
    name: notification
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/notification
    password: user
  jpa:
      hibernate:
          ddl-auto: create
      show-sql: true
  zipkin:
    base-url: http://localhost:9411
  rabbitmq:
    addresses: localhost:5672
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
rabbitmq:
  exchanges:
    internal: internal.exchange
  queues:
    notification: notification.queue
  routing-keys:
    internal-notification: internal.notification.routing-key